apiVersion: v1
kind: Service
metadata:
  name: client
spec:
  selector:
    app: client
  ports:
    - port: 80
      targetPort: 8080
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
        - name: client-app
          image: iasc-tp-grupo-3:latest
          ports:
            - containerPort: 8080
          env:
            - name: application_path
              value: ./client/client.js
          imagePullPolicy: Never